### ISSUE TITLE
DWR

### ISSUE THREAD

**Issue by clancger** [4IceG/luci-app-sms-tool#12]

**Comment by clancger** [comment]
Hi, 
Im attempting to install SMS tool on D-Link DWR921...

Ive tried the following all give the similar errors. Any suggestion pls?
luci-app-sms-tool_1.9.3-20220217_all
luci-app-sms-tool_1.9.3-20220217_all
luci-app-sms-tool_1.9.1-19092021-lc_all
sms-tool_2021-12-03-d38898f4-1_mips_24kc

Collected errors:
 * pkg_hash_check_unresolved: cannot find dependency sms-tool for luci-app-sms-tool
 * pkg_hash_fetch_best_installation_candidate: Packages for luci-app-sms-tool found, but incompatible with the architectures configured
 * opkg_install_cmd: Cannot install package luci-app-sms-tool.

**Comment by 4IceG** [comment]
Hi, I don't know what version of Openwrt you have, but install packages in this order:
1) sms-tool_2021-12-03-d38898f4-1_mips_24kc.ipk
2) luci-app-sms-tool_1.9.3-20220217_all.ipk or luci-app-sms-tool_1.9.1-19092021-lc_all.ipk

You probably know how to install packages, you can do it from the console (having copied packages eg to the / tmp folder in the router) or via LuCI using the "Upload package" option.
