### ISSUE TITLE
sms-tools for Openwrt on Raspberry Pi4B

### ISSUE THREAD

**Issue by finish475** [4IceG/luci-app-sms-tool#13]
Pls create file ipk for Raspberry Pi4B, Thanks

**Comment by 4IceG** [comment]
Hi, I haven't built images for Raspberry so I don't know if it will work, you'll have to check.

[Raspberry Pi4B Test.zip](https://github.com/4IceG/luci-app-sms-tool/files/8314400/Raspberry.Pi4B.Test.zip)
