### ISSUE TITLE
Building packages for Openwrt on Raspberry Pi4b

### ISSUE THREAD

**Issue by finish475** [4IceG/luci-app-sms-tool#14]
Hello!
I am a newbie.
I am wanting to use your tool for SierraWireless EM7565 in openwrt 21.02.1 with Raspberry Pi4 router.
I really don't know what materials are needed in combination with your source code to build the sms-tool.ipk file.
Can you give me detailed instructions please?
Thank you very much

**Comment by 4IceG** [comment]
I posted the ipk file for installation earlier in another thread for Raspberry Pi4.
I'm adding it again, for download below.
[Raspberry.Pi4B.Test.zip](https://github.com/4IceG/luci-app-sms-tool/files/8334818/Raspberry.Pi4B.Test.zip)

There are two ways to add packages from the Openwrt source folder:

```
cd feeds/luci/applications/
git clone https://github.com/4IceG/luci-app-sms-tool.git
cd ../../..
./scripts feeds update -a; ./scripts/feeds install -a
make menuconfig
```

or e.g.

```
cd packages/
git clone https://github.com/4IceG/luci-app-sms-tool.git
git pull
make package/symlinks
make menuconfig
```

You may need to correct the file paths and the number of folders to look like this:
```
feeds/luci/applications/luci-app-sms-tool/Makefile
feeds/luci/applications/sms-tool/Makefile
```
or
```
packages/luci-app-sms-tool/Makefile
packages/sms-tool/Makefile
```

**Comment by finish475** [comment]
Thank you very much,
 I have installed 2 files for RaspiberryPi4b.  But the interface opens very slowly.  Maybe need to rebuild

**Comment by 4IceG** [comment]
Everything is slow because the packet communicates with the modem on the
same interface on which data transmission can take place. I do not know
what it set, I do not know each modem, but in the application settings you
have to change the ports for communication with the modem, as is ttyUSB1
change to ttyUSB2 or other appropriate for this modem.

czw., 24 mar 2022, 01:16 użytkownik finish475 ***@***.***>
napisał:

**Comment by 4IceG** [comment]
Don't worry about it, sometimes it can pop up like this, but it doesn't
affect the operation of the application.

czw., 24 mar 2022, 15:03 użytkownik finish475 ***@***.***>
napisał:

**Comment by finish475** [comment]
Although the interface was slow, I was able to read the sms. Send sms and USSD, modem does not respond.

**Comment by 4IceG** [comment]
There are many options...

- Wrong ttyUSBX port.
- Other programs are communicating with the modem at the same time.
- The modem may not be supported by sms-tool (but I doubt it if the modem has its own diagnostic port for communication).

Anyway, you have the modem, you must know it and know what you have installed on your system, I have no other ideas.
