### ISSUE TITLE
Where's luci-app-sms-tool published?

### ISSUE THREAD

**Issue by Nowaker** [4IceG/luci-app-sms-tool#15]
Can't find it here: https://dl.eko.one.pl/openwrt-19.07/packages/arm_cortex-a9_vfpv3-d16/base/ (where `sms-tool` is found) or in any subdirectory of https://dl.eko.one.pl/openwrt-19.07/packages/arm_cortex-a9_vfpv3-d16/.

**Comment by 4IceG** [comment]
Hi, luci-app-sms-tool is only on my github and you have to install it
manually, it's not in Cezary's repository.

pt., 25 mar 2022, 17:35 użytkownik Damian Nowak ***@***.***>
napisał:

**Comment by Nowaker** [comment]
I see. The instructions are unclear then. If no `ipk` for luci-app-sms-tool is provided, this section needs to be updated.

```
#Install sms-tool.
opkg install sms-tool_2021-12-03-d38898f4-1_XXX.ipk

#Install gui.
opkg install luci-app-sms-tool_1.9.3-20211205_all.ipk
or (without luci-compat)
opkg install luci-app-sms-tool_1.9.3-20211205_all-lc.ipk
```

**Comment by Nowaker** [comment]
Here it is! https://github.com/4IceG/luci-app-sms-tool/releases

**Comment by 4IceG** [comment]
I improve installation instructions over the weekend, the package is for
the fanatics of the eko one forum anyway.

pt., 25 mar 2022, 17:48 użytkownik Damian Nowak ***@***.***>
napisał:
