### ISSUE TITLE
There is no luci-app-sms-tool in ACL

### ISSUE THREAD

**Issue by GektorUA** [4IceG/luci-app-sms-tool#21]
Hi, there is no luci-app-sms-tool in ACL package.

**Comment by 4IceG** [comment]
Hi @GektorUA , can you explain because I don't know what the problem is? ACL package?

**Comment by 4IceG** [comment]
Hi, I don't know what this package requires, but my packages (even older ones) have acl permissions file.

**Comment by 4IceG** [comment]
I don't know which version of OpenWrt you have, but for the latest release I recommend installing the JS version of the package.
https://github.com/4IceG/luci-app-sms-tool-js

**Comment by 4IceG** [comment]
The message from the luci-app-acl package explains the situation.
![obraz](https://user-images.githubusercontent.com/59826889/220421894-d0a6e97c-64f8-4cb4-a552-3d741469f6c1.png)

**Comment by 4IceG** [comment]
It's possible that the luci-app-acl package needs a specific section in the acl file.

I see that the luci-app-acl package is new, so I recommend using the new package in JS (I will not develop this package anymore).
