### ISSUE TITLE
Error trying to go to Configuration tab

### ISSUE THREAD

**Issue by jimbolaya** [4IceG/luci-app-sms-tool#23]
I am running OpenWRT v22.03.5 on x86_64.

I've downloaded and installed luci-app-sms-tool_1.9.6-20230501_all.ipk and  sms-tool_2021-12-03-d38898f4-1_x86_64.ipk (since there didn't seem to be a newer one).

I've got a Quectel EC25-G modem installed and it's working great. Everything I've tried with this tool has worked, sending and receiving sms and the AT command interface. 

However, when I click on the Configuration tab, I get a LuCI error:

```
/usr/lib/lua/luci/dispatcher.lua:1379: module 'luci.cbi' not found:
	no field package.preload['luci.cbi']
	no file './luci/cbi.lua'
	no file '/usr/share/lua/luci/cbi.lua'
	no file '/usr/share/lua/luci/cbi/init.lua'
	no file '/usr/lib/lua/luci/cbi.lua'
	no file '/usr/lib/lua/luci/cbi/init.lua'
	no file './luci/cbi.so'
	no file '/usr/lib/lua/luci/cbi.so'
	no file '/usr/lib/lua/loadall.so'
	no file './luci.so'
	no file '/usr/lib/lua/luci.so'
	no file '/usr/lib/lua/loadall.so'
stack traceback:
	[C]: in function 'require'
	/usr/lib/lua/luci/dispatcher.lua:1379: in function '_cbi'
	/usr/lib/lua/luci/dispatcher.lua:1056: in function 'dispatch'
	/usr/lib/lua/luci/dispatcher.lua:483: in function </usr/lib/lua/luci/dispatcher.lua:482>
```

Did I miss a dependency?

I'm not sure how to troubleshoot this myself, so I thought I should submit a report.

Thank you for making this available, it should come in handy.

**Comment by 4IceG** [comment]
Hi @jimbolaya ,
You are using a fairly up-to-date release of OpenWrt so I would recommend installing this version of the package https://github.com/4IceG/luci-app-sms-tool-js. An older version of the package will not work properly even with the luci-compat package installed (missing dependency).

At the beginning of the package description I explained for which version of OpenWrt the package is recommended, as you can see users do not read the description ;).

**Comment by jimbolaya** [comment]
Oops, sorry.

**Comment by 4IceG** [comment]
Nothing wrong, I just hoped that I described everything very simply, and yet there are still problems and questions.

![Bez nazwasdasdy](https://github.com/4IceG/luci-app-sms-tool/assets/59826889/0f4f174f-ed96-4c38-805c-101ba1ffc953)
