### ISSUE TITLE
JSON.parse fails on special invisible characters

### ISSUE THREAD

**Issue by helllamer** [4IceG/luci-app-sms-tool#25]
The problem:
- Sms messages counter is visible
- No sms messages displayed in table bottom.
- See screenshot:
- Look at mouse pointer (bottom right) -- `\u0011` character in `.[0].sender`

![Снимок экрана от 2024-01-03 13-30-16](https://github.com/4IceG/luci-app-sms-tool/assets/681744/f7101ca3-8f2f-491d-92b6-fdd95d836b3d)

Steps to reproduce:
- Buggy SMS message received from operator with garbage inside "sender" field:
![Снимок экрана от 2024-01-03 13-20-58](https://github.com/4IceG/luci-app-sms-tool/assets/681744/84e168f8-6187-4632-9860-7e6eb6d988aa)
![Снимок экрана от 2024-01-03 13-36-13](https://github.com/4IceG/luci-app-sms-tool/assets/681744/09b3cfaf-3078-4daf-ac83-cedc93be34bb)

![Снимок экрана от 2024-01-03 13-24-47](https://github.com/4IceG/luci-app-sms-tool/assets/681744/2e5b82b5-67ec-408b-9017-79e0b6edca48)

In my example, there are `\u0011` inside `sender` field, so browser failed to `JSON.parse()`.

Looks like, related problem in SO https://stackoverflow.com/questions/28008852/json-parse-failing-on-valid-json-have-escaped-control-characters-if

**Comment by 4IceG** [comment]
Hi @helllamer , 

Problem is known https://github.com/4IceG/luci-app-sms-tool-js/issues/9 and should be solved.

**Comment by helllamer** [comment]
Closing as duplicate of #9
