### ISSUE TITLE
No Chinese language package

### ISSUE THREAD

**Issue by dragon888888888888** [4IceG/luci-app-sms-tool#26]
Use this without Chinese package, luci-app-sms-tool-JS Chinese language package Not available here，use luci-app-sms-tool-JS luci cannot compile the SMS package even if the SMS menu appears.Using luci-app-sms-tool can compile successfully, but there is no Chinese package. openwrt 23.05

**Comment by dragon888888888888** [comment]
Already found a solution

**Comment by ChrisYH20** [comment]
> Already found a solution

Can you share your resources?

**Comment by 4IceG** [comment]
Hi @ChrisYH20 @dragon888888888888 
Please share the correct/good translation and I will add it to repository.

For example
https://github.com/Toolcen/luci-app-sms-tool/blob/master/luci-app-sms-tool/po/zh-cn/sms-tool.po

**Comment by dragon888888888888** [comment]
> 你好@ChrisYH20 @dragon888888888888 请分享正确/好的翻译，我会将其添加到存储库。
> 
> 例如 https://github.com/Toolcen/luci-app-sms-tool/blob/master/luci-app-sms-tool/po/zh-cn/sms-tool.po

https://github.com/kiddin9/openwrt-packages/blob/master/luci-app-sms-tool/po/zh-cn/sms-tool.po

Found here, I don't mean how good its translation is, I just mean that I put it in the ../pacdage/ kernel directory, and then it can be found after make menuconfig。
If you use this luci-app-sms-tool , it cannot be found after make menuconfig. luci-app-sms-tool-JS can be found, but it does not have a Chinese package.
