### ISSUE TITLE
Messages are garbled when sending Chinese

### ISSUE THREAD

**Issue by ChrisYH20** [4IceG/luci-app-sms-tool#27]
When sending a Chinese message, each Chinese character in the message will become a "?"
But the received Chinese message will not be garbled.

**Comment by 4IceG** [comment]
Hi @ChrisYH20 
Description of sms-tool from https://eko.one.pl/?p=openwrt-sms_tool
> sms_tool supports both PDU and UCS2 encoding, so there should be no problems with national characters (at least when displaying received SMS messages). It also supports multi-part SMS messages and correctly decodes the sender (in the form of a number or alphanumeric name).

> Only SMS-DELIVER messages are decoded, program does not support all possible types of SMS.

It appears that the problem with outgoing messages was known.

**Comment by ChrisYH20** [comment]
Thanks
