### ISSUE TITLE
Received SMS not displayed on version 1.8.4

### ISSUE THREAD

**Issue by wentuq** [4IceG/luci-app-sms-tool#4]
Hi,
First I wanted to thanks you for software you made :)
There is a regression in 1.8.4 - in tab "Received Messages" received SMS are not displayed nothing is showing up. Messages are stored in "SIM Card"
When I downgraded to 1.8.3 everything was working perfectly.

**Comment by 4IceG** [comment]
Cześć :) dzięki za info już szukam gdzie i co jest nie halo.

**Comment by 4IceG** [comment]
Ok, jeszcze ciepla paczka, ale juz powinno byc dobrze.
[fixed.zip](https://github.com/4IceG/luci-app-sms-tool/files/6137402/fixed.zip)

**Comment by wentuq** [comment]
Potwierdzam, działa :)
