### ISSUE TITLE
Endless loop without pause

### ISSUE THREAD

**Issue by HyP3r-** [4IceG/luci-app-sms-tool#5]
There is a small bug in the smsled-init.sh program. If the notification is deactivated the endless loop runs without interruption. I would add a small sleep to the corresponding line: https://github.com/4IceG/luci-app-sms-tool/blob/0a1053128afcee184353d1eeebe2330e8b32ca9f/luci-app-sms-tool/root/sbin/smsled-init.sh#L18

**Comment by 4IceG** [comment]
If notifications are not enabled, the looped process should not work. If
the code can be corrected then I am open to suggestions for fixed script.

sob., 14 sie 2021, 00:10 użytkownik HyP3r ***@***.***>
napisał:

**Comment by HyP3r-** [comment]
As I understood the code it is necessary that the script runs constantly in the background because it can always happen that the user can activate the LED indicators. Therefore the loop must run constantly.

My solution suggestion would be quite simply the following:
```
#!/bin/sh
# Copyright 2020 Rafał Wabik (IceG) - From eko.one.pl forum
# Licensed to the GNU General Public License v3.0.

sleep 1m
CT=$(uci -q get sms_tool.general.checktime)
TX=$(echo $CT | tr -dc '0-9')
TM=$(($TX * 60))

while [ 1 ]; do 
	LED=$(uci -q get sms_tool.general.lednotify)
	if [ $LED == "1" ]; then
    	sleep $TM
		(/sbin/smsled.sh >/dev/null 2>&1 )&
		continue
	fi
	sleep 1
done
 
exit 0
```

**Comment by 4IceG** [comment]
I will add this delay to the script as soon as I am at the computer. Thank
you for the suggestions.

sob., 14 sie 2021, 00:56 użytkownik HyP3r ***@***.***>
napisał:

**Comment by HyP3r-** [comment]
If you want I can create a Pull Request.

**Comment by 4IceG** [comment]
No PR need, I've already done the package updates.

sob., 14 sie 2021, 12:14 użytkownik HyP3r ***@***.***>
napisał:

**Comment by HyP3r-** [comment]
Ok. Thank you very much. Although I must say that your indentations in the code are very creative.

**Comment by 4IceG** [comment]
Thanks, but I would say more that I did what I could and it works somehow.

sob., 14 sie 2021, 12:29 użytkownik HyP3r ***@***.***>
napisał:
