### ISSUE TITLE
Configuraion tab not opened - error in luci

### ISSUE THREAD

**Issue by Harwesta** [4IceG/luci-app-sms-tool#7]
Hi!

Orange pi zero
openwrt-19.07 branch (git-21.044.30835-34e0d65) / OpenWrt 19.07.7 r11306-c4a6851c72 
Error on configuration tab:
http://192.168.1.1/cgi-bin/luci/admin/modem/sms/smsconfig

/usr/lib/lua/luci/cbi.lua:53: /usr/lib/lua/luci/model/cbi/modem/smsconfig.lua:219: '=' expected near 'local'
stack traceback:
	[C]: in function 'assert'
	/usr/lib/lua/luci/cbi.lua:53: in function 'load'
	/usr/lib/lua/luci/dispatcher.lua:1340: in function '_cbi'
	/usr/lib/lua/luci/dispatcher.lua:1023: in function 'dispatch'
	/usr/lib/lua/luci/dispatcher.lua:478: in function </usr/lib/lua/luci/dispatcher.lua:477>

**Comment by 4IceG** [comment]
Hi, it looks like a bug with luci itself and not with the application, you
are the first person to report something like this. Try to clear the cache
in Luci and the browser, if that doesn't help, try to install the
application on a clean system (after factory reset).

śr., 8 wrz 2021, 07:44 użytkownik Harwesta ***@***.***>
napisał:

**Comment by Harwesta** [comment]
Ok, i try it.
But this a first (and clean) starting after compiling firmware with your module :)
My colleague try my firmware and report same issue.

**Comment by 4IceG** [comment]
If you compile by yourself, try to build the image on the newest Openwrt
source possible. I tested the applications only on versions 21.x and I do
not know where they stopped with patches in older versions.

śr., 8 wrz 2021, 16:20 użytkownik Harwesta ***@***.***>
napisał:

**Comment by Harwesta** [comment]
Ok.
I build firmware on openwrt 19.07.07 because a 21.02 unstable
