### ISSUE TITLE
Can I add Scripts when recieved SMS ?

### ISSUE THREAD

**Issue by andyhuai** [4IceG/luci-app-sms-tool#8]
Can I add Scripts when recieved SMS ?

I want to send SMS to my phone when recieved a sms

**Comment by 4IceG** [comment]
Hi, I'm sorry, but the application does not have this functionality at the moment. 

Of course, you can add a script that would try to perform the appropriate action, but at the moment it is probably easier to use smstools3.

**Comment by andyhuai** [comment]
I see, thx
