### ISSUE TITLE
My luci is old edition,no luci-comat

### ISSUE THREAD

**Issue by wuxeon** [4IceG/luci-app-sms-tool#9]
Couldn't install luci-app-sms-tool.

 pkg_hash_check_unresolved: cannot find dependency luci-compat for luci-app-sms-tool
 * pkg_hash_fetch_best_installation_candidate: Packages for luci-app-sms-tool found, but incompatible with the architectures configured

**Comment by 4IceG** [comment]
Hi,
If you have sms-tool installed, you can manually upload files from
luci-app-sms-tool. Or you can wait because I'm compiling a new image today
so I can make a package without luci-compat.

pon., 4 paź 2021, 04:34 użytkownik wuxeon ***@***.***>
napisał:

**Comment by wuxeon** [comment]
Thank you for your reply.
My English is not good.
Thank you.

**Comment by wuxeon** [comment]
The 
luci-app-3ginfo has been installed sucessfully,but the luci menu still not MODEM tab exist...

**Comment by 4IceG** [comment]
You probably need to clear the cache for LuCi, you can do this with "rm -rf
/tmp/luci*" or restart the router.

pon., 4 paź 2021, 05:28 użytkownik wuxeon ***@***.***>
napisał:

**Comment by 4IceG** [comment]
Try install
https://github.com/4IceG/luci-app-sms-tool/releases/download/1.9.1-19092021/luci-app-sms-tool_1.9.1-19092021-lc_all.ipk

**Comment by wuxeon** [comment]
It work fine except send message。
error info：
/usr/lib/lua/luci/template.lua:97: Failed to execute template 'modem/sendsms'.
A runtime error occured: [string "/usr/lib/lua/luci/view/modem/sendsms.htm"]:5: calling 'get' on bad self (string expected, got table)
stack traceback:
	[C]: in function 'assert'
	/usr/lib/lua/luci/dispatcher.lua:469: in function 'dispatch'
	/usr/lib/lua/luci/dispatcher.lua:121: in function </usr/lib/lua/luci/dispatcher.lua:120>

thankyou。

Can you compile the 3ginfo lc？

**Comment by 4IceG** [comment]
As for the sms sending error, I see that it is Luci's error, so here I
would recommend updating. 3ginfo I can do but only in the evening because
now I'm not at the computer.

pon., 4 paź 2021, 12:04 użytkownik wuxeon ***@***.***>
napisał:

**Comment by wuxeon** [comment]
Ok, thanks.

**Comment by 4IceG** [comment]
Try install
https://github.com/4IceG/luci-app-3ginfo/releases/download/1.3.3/luci-app-3ginfo_1.3.3-lc_all.ipk
